# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Api.Accounts do
  @moduledoc """
  API calls for all endpoints tagged `Accounts`.
  """

  alias PeerTube.Connection
  import PeerTube.RequestBuilder


  @doc """
  List accounts

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :start (integer()): Offset used to paginate results
    - :count (integer()): Number of items to return
    - :sort (String.t): Sort column
  ## Returns

  {:ok, [%Account{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec accounts_get(Tesla.Env.client, keyword()) :: {:ok, list(PeerTube.Model.Account.t)} | {:error, Tesla.Env.t}
  def accounts_get(connection, opts \\ []) do
    optional_params = %{
      :"start" => :query,
      :"count" => :query,
      :"sort" => :query
    }
    %{}
    |> method(:get)
    |> url("/accounts")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, [%PeerTube.Model.Account{}]}
    ])
  end

  @doc """
  Get an account

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - name (String.t): The username or handle of the account
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, PeerTube.Model.Account.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec accounts_name_get(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, PeerTube.Model.Account.t} | {:error, Tesla.Env.t}
  def accounts_name_get(connection, name, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/accounts/#{name}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %PeerTube.Model.Account{}},
      { 404, false}
    ])
  end

  @doc """
  List ratings of an account

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - name (String.t): The username or handle of the account
  - opts (KeywordList): [optional] Optional parameters
    - :start (integer()): Offset used to paginate results
    - :count (integer()): Number of items to return
    - :sort (String.t): Sort column
    - :rating (String.t): Optionally filter which ratings to retrieve
  ## Returns

  {:ok, [%VideoRating{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec accounts_name_ratings_get(Tesla.Env.client, String.t, keyword()) :: {:ok, list(PeerTube.Model.VideoRating.t)} | {:error, Tesla.Env.t}
  def accounts_name_ratings_get(connection, name, opts \\ []) do
    optional_params = %{
      :"start" => :query,
      :"count" => :query,
      :"sort" => :query,
      :"rating" => :query
    }
    %{}
    |> method(:get)
    |> url("/accounts/#{name}/ratings")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, [%PeerTube.Model.VideoRating{}]}
    ])
  end

  @doc """
  List video channels of an account

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - name (String.t): The username or handle of the account
  - opts (KeywordList): [optional] Optional parameters
    - :with_stats (boolean()): include view statistics for the last 30 days (only if authentified as the account user)
    - :start (integer()): Offset used to paginate results
    - :count (integer()): Number of items to return
    - :sort (String.t): Sort column
  ## Returns

  {:ok, map()} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec accounts_name_video_channels_get(Tesla.Env.client, String.t, keyword()) :: {:ok, Map.t} | {:error, Tesla.Env.t}
  def accounts_name_video_channels_get(connection, name, opts \\ []) do
    optional_params = %{
      :"withStats" => :query,
      :"start" => :query,
      :"count" => :query,
      :"sort" => :query
    }
    %{}
    |> method(:get)
    |> url("/accounts/#{name}/video-channels")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, false}
    ])
  end

  @doc """
  List videos of an account

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - name (String.t): The username or handle of the account
  - opts (KeywordList): [optional] Optional parameters
    - :category_one_of (OneOfintegerarray): category id of the video (see [/videos/categories](#tag/Video/paths/~1videos~1categories/get))
    - :tags_one_of (OneOfstringarray): tag(s) of the video
    - :tags_all_of (OneOfstringarray): tag(s) of the video, where all should be present in the video
    - :licence_one_of (OneOfintegerarray): licence id of the video (see [/videos/licences](#tag/Video/paths/~1videos~1licences/get))
    - :language_one_of (OneOfstringarray): language id of the video (see [/videos/languages](#tag/Video/paths/~1videos~1languages/get)). Use `_unknown` to filter on videos that don't have a video language
    - :nsfw (String.t): whether to include nsfw videos, if any
    - :filter (String.t): Special filters which might require special rights:  * `local` - only videos local to the instance  * `all-local` - only videos local to the instance, but showing private and unlisted videos (requires Admin privileges)  * `all` - all videos, showing private and unlisted videos (requires Admin privileges) 
    - :skip_count (String.t): if you don't need the `total` in the response
    - :start (integer()): Offset used to paginate results
    - :count (integer()): Number of items to return
    - :sort (String.t): Sort videos by criteria
  ## Returns

  {:ok, PeerTube.Model.VideoListResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec accounts_name_videos_get(Tesla.Env.client, String.t, keyword()) :: {:ok, PeerTube.Model.VideoListResponse.t} | {:error, Tesla.Env.t}
  def accounts_name_videos_get(connection, name, opts \\ []) do
    optional_params = %{
      :"categoryOneOf" => :query,
      :"tagsOneOf" => :query,
      :"tagsAllOf" => :query,
      :"licenceOneOf" => :query,
      :"languageOneOf" => :query,
      :"nsfw" => :query,
      :"filter" => :query,
      :"skipCount" => :query,
      :"start" => :query,
      :"count" => :query,
      :"sort" => :query
    }
    %{}
    |> method(:get)
    |> url("/accounts/#{name}/videos")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %PeerTube.Model.VideoListResponse{}}
    ])
  end
end
