# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Api.InstanceFollows do
  @moduledoc """
  API calls for all endpoints tagged `InstanceFollows`.
  """

  alias PeerTube.Connection
  import PeerTube.RequestBuilder


  @doc """
  List instance followers

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :start (integer()): Offset used to paginate results
    - :count (integer()): Number of items to return
    - :sort (String.t): Sort column
  ## Returns

  {:ok, [%Follow{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec server_followers_get(Tesla.Env.client, keyword()) :: {:ok, list(PeerTube.Model.Follow.t)} | {:error, Tesla.Env.t}
  def server_followers_get(connection, opts \\ []) do
    optional_params = %{
      :"start" => :query,
      :"count" => :query,
      :"sort" => :query
    }
    %{}
    |> method(:get)
    |> url("/server/followers")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, [%PeerTube.Model.Follow{}]}
    ])
  end

  @doc """
  List instances followed by the server

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :state (String.t): 
    - :actor_type (String.t): 
    - :start (integer()): Offset used to paginate results
    - :count (integer()): Number of items to return
    - :sort (String.t): Sort column
  ## Returns

  {:ok, [%Follow{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec server_following_get(Tesla.Env.client, keyword()) :: {:ok, list(PeerTube.Model.Follow.t)} | {:error, Tesla.Env.t}
  def server_following_get(connection, opts \\ []) do
    optional_params = %{
      :"state" => :query,
      :"actorType" => :query,
      :"start" => :query,
      :"count" => :query,
      :"sort" => :query
    }
    %{}
    |> method(:get)
    |> url("/server/following")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, [%PeerTube.Model.Follow{}]}
    ])
  end

  @doc """
  Unfollow a server

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - host (String.t): The host to unfollow 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec server_following_host_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def server_following_host_delete(connection, host, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/server/following/#{host}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 201, false}
    ])
  end

  @doc """
  Follow a server

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :body (InlineObject): 
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec server_following_post(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def server_following_post(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }
    %{}
    |> method(:post)
    |> url("/server/following")
    |> add_optional_params(optional_params, opts)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 204, false},
      { 500, false}
    ])
  end
end
