# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Api.MySubscriptions do
  @moduledoc """
  API calls for all endpoints tagged `MySubscriptions`.
  """

  alias PeerTube.Connection
  import PeerTube.RequestBuilder


  @doc """
  Get if subscriptions exist for my user

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - uris ([String.t]): list of uris to check if each is part of the user subscriptions
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, map()} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec users_me_subscriptions_exist_get(Tesla.Env.client, list(String.t), keyword()) :: {:ok, Map.t} | {:error, Tesla.Env.t}
  def users_me_subscriptions_exist_get(connection, uris, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/users/me/subscriptions/exist")
    |> add_param(:query, :"uris", uris)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, false}
    ])
  end

  @doc """
  Get my user subscriptions

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :start (integer()): Offset used to paginate results
    - :count (integer()): Number of items to return
    - :sort (String.t): Sort column
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec users_me_subscriptions_get(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def users_me_subscriptions_get(connection, opts \\ []) do
    optional_params = %{
      :"start" => :query,
      :"count" => :query,
      :"sort" => :query
    }
    %{}
    |> method(:get)
    |> url("/users/me/subscriptions")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, false}
    ])
  end

  @doc """
  Add subscription to my user

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :body (InlineObject1): 
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec users_me_subscriptions_post(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def users_me_subscriptions_post(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }
    %{}
    |> method(:post)
    |> url("/users/me/subscriptions")
    |> add_optional_params(optional_params, opts)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, false}
    ])
  end

  @doc """
  Delete subscription of my user

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - subscription_handle (String.t): The subscription handle
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec users_me_subscriptions_subscription_handle_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def users_me_subscriptions_subscription_handle_delete(connection, subscription_handle, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/users/me/subscriptions/#{subscription_handle}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, false}
    ])
  end

  @doc """
  Get subscription of my user

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - subscription_handle (String.t): The subscription handle
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, PeerTube.Model.VideoChannel.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec users_me_subscriptions_subscription_handle_get(Tesla.Env.client, String.t, keyword()) :: {:ok, PeerTube.Model.VideoChannel.t} | {:error, Tesla.Env.t}
  def users_me_subscriptions_subscription_handle_get(connection, subscription_handle, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/users/me/subscriptions/#{subscription_handle}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %PeerTube.Model.VideoChannel{}}
    ])
  end

  @doc """
  List videos of subscriptions of my user

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :category_one_of (OneOfintegerarray): category id of the video (see [/videos/categories](#tag/Video/paths/~1videos~1categories/get))
    - :tags_one_of (OneOfstringarray): tag(s) of the video
    - :tags_all_of (OneOfstringarray): tag(s) of the video, where all should be present in the video
    - :licence_one_of (OneOfintegerarray): licence id of the video (see [/videos/licences](#tag/Video/paths/~1videos~1licences/get))
    - :language_one_of (OneOfstringarray): language id of the video (see [/videos/languages](#tag/Video/paths/~1videos~1languages/get)). Use `_unknown` to filter on videos that don't have a video language
    - :nsfw (String.t): whether to include nsfw videos, if any
    - :filter (String.t): Special filters which might require special rights:  * `local` - only videos local to the instance  * `all-local` - only videos local to the instance, but showing private and unlisted videos (requires Admin privileges)  * `all` - all videos, showing private and unlisted videos (requires Admin privileges) 
    - :skip_count (String.t): if you don't need the `total` in the response
    - :start (integer()): Offset used to paginate results
    - :count (integer()): Number of items to return
    - :sort (String.t): Sort videos by criteria
  ## Returns

  {:ok, PeerTube.Model.VideoListResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec users_me_subscriptions_videos_get(Tesla.Env.client, keyword()) :: {:ok, PeerTube.Model.VideoListResponse.t} | {:error, Tesla.Env.t}
  def users_me_subscriptions_videos_get(connection, opts \\ []) do
    optional_params = %{
      :"categoryOneOf" => :query,
      :"tagsOneOf" => :query,
      :"tagsAllOf" => :query,
      :"licenceOneOf" => :query,
      :"languageOneOf" => :query,
      :"nsfw" => :query,
      :"filter" => :query,
      :"skipCount" => :query,
      :"start" => :query,
      :"count" => :query,
      :"sort" => :query
    }
    %{}
    |> method(:get)
    |> url("/users/me/subscriptions/videos")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %PeerTube.Model.VideoListResponse{}}
    ])
  end
end
