# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Api.VideoRates do
  @moduledoc """
  API calls for all endpoints tagged `VideoRates`.
  """

  alias PeerTube.Connection
  import PeerTube.RequestBuilder


  @doc """
  Get rate of my user for a video

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - video_id (String.t): The video id 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, PeerTube.Model.GetMeVideoRating.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec users_me_videos_video_id_rating_get(Tesla.Env.client, String.t, keyword()) :: {:ok, PeerTube.Model.GetMeVideoRating.t} | {:error, Tesla.Env.t}
  def users_me_videos_video_id_rating_get(connection, video_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/users/me/videos/#{video_id}/rating")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %PeerTube.Model.GetMeVideoRating{}}
    ])
  end

  @doc """
  Like/dislike a video

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - id (OneOfintegerUuid): The object id or uuid
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec videos_id_rate_put(Tesla.Env.client, PeerTube.Model.OneOfintegerUuid.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def videos_id_rate_put(connection, id, _opts \\ []) do
    %{}
    |> method(:put)
    |> url("/videos/#{id}/rate")
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 204, false},
      { 404, false}
    ])
  end
end
