# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Api.VideoMirroring do
  @moduledoc """
  API calls for all endpoints tagged `VideoMirroring`.
  """

  alias PeerTube.Connection
  import PeerTube.RequestBuilder


  @doc """
  List videos being mirrored

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - target (String.t): direction of the mirror
  - opts (KeywordList): [optional] Optional parameters
    - :start (integer()): Offset used to paginate results
    - :count (integer()): Number of items to return
    - :sort (String.t): Sort abuses by criteria
  ## Returns

  {:ok, [%VideoRedundancy{}, ...]} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec redundancy_videos_get(Tesla.Env.client, String.t, keyword()) :: {:ok, list(PeerTube.Model.VideoRedundancy.t)} | {:error, Tesla.Env.t}
  def redundancy_videos_get(connection, target, opts \\ []) do
    optional_params = %{
      :"start" => :query,
      :"count" => :query,
      :"sort" => :query
    }
    %{}
    |> method(:get)
    |> url("/redundancy/videos")
    |> add_param(:query, :"target", target)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, [%PeerTube.Model.VideoRedundancy{}]}
    ])
  end

  @doc """
  Mirror a video

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :body (InlineObject27): 
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec redundancy_videos_post(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def redundancy_videos_post(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }
    %{}
    |> method(:post)
    |> url("/redundancy/videos")
    |> add_optional_params(optional_params, opts)
    |> ensure_body()
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 204, false},
      { 400, false},
      { 404, false},
      { 409, false}
    ])
  end

  @doc """
  Delete a mirror done on a video

  ## Parameters

  - connection (PeerTube.Connection): Connection to server
  - redundancy_id (String.t): id of an existing redundancy on a video
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, nil} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec redundancy_videos_redundancy_id_delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def redundancy_videos_redundancy_id_delete(connection, redundancy_id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/redundancy/videos/#{redundancy_id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 204, false},
      { 404, false}
    ])
  end
end
