# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.AbusesVideo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"startAt",
    :"endAt"
  ]

  @type t :: %__MODULE__{
    :"id" => float() | nil,
    :"startAt" => integer() | nil,
    :"endAt" => integer() | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.AbusesVideo do
  def decode(value, _options) do
    value
  end
end

