# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.AccountAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"userId",
    :"displayName",
    :"description"
  ]

  @type t :: %__MODULE__{
    :"userId" => String.t | nil,
    :"displayName" => String.t | nil,
    :"description" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.AccountAllOf do
  def decode(value, _options) do
    value
  end
end

