# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.Actor do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"url",
    :"name",
    :"host",
    :"followingCount",
    :"followersCount",
    :"createdAt",
    :"updatedAt",
    :"avatar"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"url" => String.t | nil,
    :"name" => String.t | nil,
    :"host" => String.t | nil,
    :"followingCount" => integer() | nil,
    :"followersCount" => integer() | nil,
    :"createdAt" => DateTime.t | nil,
    :"updatedAt" => DateTime.t | nil,
    :"avatar" => PeerTube.Model.ActorImage.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.Actor do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"avatar", :struct, PeerTube.Model.ActorImage, options)
  end
end

