# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ActorImage do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"path",
    :"createdAt",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"path" => String.t | nil,
    :"createdAt" => DateTime.t | nil,
    :"updatedAt" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ActorImage do
  def decode(value, _options) do
    value
  end
end

