# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ActorInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"displayName",
    :"host",
    :"avatar"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"name" => String.t | nil,
    :"displayName" => String.t | nil,
    :"host" => String.t | nil,
    :"avatar" => PeerTube.Model.ActorInfoAvatar.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ActorInfo do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"avatar", :struct, PeerTube.Model.ActorInfoAvatar, options)
  end
end

