# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.AddUser do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"username",
    :"password",
    :"email",
    :"videoQuota",
    :"videoQuotaDaily",
    :"channelName",
    :"role",
    :"adminFlags"
  ]

  @type t :: %__MODULE__{
    :"username" => String.t,
    :"password" => String.t,
    :"email" => String.t,
    :"videoQuota" => integer(),
    :"videoQuotaDaily" => integer(),
    :"channelName" => String.t | nil,
    :"role" => PeerTube.Model.UserRole.t,
    :"adminFlags" => PeerTube.Model.UserAdminFlags.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.AddUser do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"role", :struct, PeerTube.Model.UserRole, options)
    |> deserialize(:"adminFlags", :struct, PeerTube.Model.UserAdminFlags, options)
  end
end

