# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.AddUserResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"user"
  ]

  @type t :: %__MODULE__{
    :"user" => PeerTube.Model.AddUserResponseUser.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.AddUserResponse do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"user", :struct, PeerTube.Model.AddUserResponseUser, options)
  end
end

