# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.CommentThreadPostResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"comment"
  ]

  @type t :: %__MODULE__{
    :"comment" => PeerTube.Model.VideoComment.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.CommentThreadPostResponse do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"comment", :struct, PeerTube.Model.VideoComment, options)
  end
end

