# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.Follow do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"follower",
    :"following",
    :"score",
    :"state",
    :"createdAt",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"follower" => PeerTube.Model.Actor.t | nil,
    :"following" => PeerTube.Model.Actor.t | nil,
    :"score" => float() | nil,
    :"state" => String.t | nil,
    :"createdAt" => DateTime.t | nil,
    :"updatedAt" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.Follow do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"follower", :struct, PeerTube.Model.Actor, options)
    |> deserialize(:"following", :struct, PeerTube.Model.Actor, options)
  end
end

