# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineResponse2006 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"total",
    :"data"
  ]

  @type t :: %__MODULE__{
    :"total" => integer() | nil,
    :"data" => [PeerTube.Model.VideoPlaylist.t] | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineResponse2006 do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :list, PeerTube.Model.VideoPlaylist, options)
  end
end

