# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineResponse2007 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"videoPlaylist"
  ]

  @type t :: %__MODULE__{
    :"videoPlaylist" => PeerTube.Model.InlineResponse2007VideoPlaylist.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineResponse2007 do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"videoPlaylist", :struct, PeerTube.Model.InlineResponse2007VideoPlaylist, options)
  end
end

