# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineResponse2005 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"banner"
  ]

  @type t :: %__MODULE__{
    :"banner" => PeerTube.Model.ActorImage.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineResponse2005 do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"banner", :struct, PeerTube.Model.ActorImage, options)
  end
end

