# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineResponse2009 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"videoId"
  ]

  @type t :: %__MODULE__{
    :"videoId" => [PeerTube.Model.InlineResponse2009VideoId.t] | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineResponse2009 do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"videoId", :list, PeerTube.Model.InlineResponse2009VideoId, options)
  end
end

