# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineObject11 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"reason",
    :"predefinedReasons",
    :"video",
    :"comment",
    :"account"
  ]

  @type t :: %__MODULE__{
    :"reason" => String.t,
    :"predefinedReasons" => [String.t] | nil,
    :"video" => PeerTube.Model.AbusesVideo.t | nil,
    :"comment" => PeerTube.Model.AbusesComment.t | nil,
    :"account" => PeerTube.Model.AbusesAccount.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineObject11 do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"video", :struct, PeerTube.Model.AbusesVideo, options)
    |> deserialize(:"comment", :struct, PeerTube.Model.AbusesComment, options)
    |> deserialize(:"account", :struct, PeerTube.Model.AbusesAccount, options)
  end
end

