# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineResponse2008 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"videoPlaylistElement"
  ]

  @type t :: %__MODULE__{
    :"videoPlaylistElement" => PeerTube.Model.InlineResponse2008VideoPlaylistElement.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineResponse2008 do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"videoPlaylistElement", :struct, PeerTube.Model.InlineResponse2008VideoPlaylistElement, options)
  end
end

