# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineObject20 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"startPosition",
    :"insertAfterPosition",
    :"reorderLength"
  ]

  @type t :: %__MODULE__{
    :"startPosition" => integer(),
    :"insertAfterPosition" => integer(),
    :"reorderLength" => integer() | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineObject20 do
  def decode(value, _options) do
    value
  end
end

