# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineObject3 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"newVideoFromSubscription",
    :"newCommentOnMyVideo",
    :"abuseAsModerator",
    :"videoAutoBlacklistAsModerator",
    :"blacklistOnMyVideo",
    :"myVideoPublished",
    :"myVideoImportFinished",
    :"newFollow",
    :"newUserRegistration",
    :"commentMention",
    :"newInstanceFollower",
    :"autoInstanceFollowing"
  ]

  @type t :: %__MODULE__{
    :"newVideoFromSubscription" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"newCommentOnMyVideo" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"abuseAsModerator" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"videoAutoBlacklistAsModerator" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"blacklistOnMyVideo" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"myVideoPublished" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"myVideoImportFinished" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"newFollow" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"newUserRegistration" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"commentMention" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"newInstanceFollower" => PeerTube.Model.NotificationSettingValue.t | nil,
    :"autoInstanceFollowing" => PeerTube.Model.NotificationSettingValue.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineObject3 do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"newVideoFromSubscription", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"newCommentOnMyVideo", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"abuseAsModerator", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"videoAutoBlacklistAsModerator", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"blacklistOnMyVideo", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"myVideoPublished", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"myVideoImportFinished", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"newFollow", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"newUserRegistration", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"commentMention", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"newInstanceFollower", :struct, PeerTube.Model.NotificationSettingValue, options)
    |> deserialize(:"autoInstanceFollowing", :struct, PeerTube.Model.NotificationSettingValue, options)
  end
end

