# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineObject12 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"state",
    :"moderationComment"
  ]

  @type t :: %__MODULE__{
    :"state" => PeerTube.Model.AbuseStateSet.t | nil,
    :"moderationComment" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineObject12 do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"state", :struct, PeerTube.Model.AbuseStateSet, options)
  end
end

