# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineObject29 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"settings"
  ]

  @type t :: %__MODULE__{
    :"settings" => %{optional(String.t) => map()} | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineObject29 do
  def decode(value, _options) do
    value
  end
end

