# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineObject do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"hosts"
  ]

  @type t :: %__MODULE__{
    :"hosts" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineObject do
  def decode(value, _options) do
    value
  end
end

