# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.InlineObject19 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"videoId",
    :"startTimestamp",
    :"stopTimestamp"
  ]

  @type t :: %__MODULE__{
    :"videoId" => integer(),
    :"startTimestamp" => integer() | nil,
    :"stopTimestamp" => integer() | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.InlineObject19 do
  def decode(value, _options) do
    value
  end
end

