# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.LiveVideoUpdate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"saveReplay",
    :"permanentLive"
  ]

  @type t :: %__MODULE__{
    :"saveReplay" => boolean() | nil,
    :"permanentLive" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.LiveVideoUpdate do
  def decode(value, _options) do
    value
  end
end

