# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.NotificationComment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"threadId",
    :"video",
    :"account"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"threadId" => integer() | nil,
    :"video" => PeerTube.Model.VideoInfo.t | nil,
    :"account" => PeerTube.Model.ActorInfo.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.NotificationComment do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"video", :struct, PeerTube.Model.VideoInfo, options)
    |> deserialize(:"account", :struct, PeerTube.Model.ActorInfo, options)
  end
end

