# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.NotificationVideoAbuse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"video"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"video" => VideoInfo | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.NotificationVideoAbuse do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"video", :struct, PeerTube.Model.VideoInfo, options)
  end
end

