# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.NotificationActorFollow do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"follower",
    :"state",
    :"following"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"follower" => PeerTube.Model.ActorInfo.t | nil,
    :"state" => String.t | nil,
    :"following" => PeerTube.Model.NotificationActorFollowFollowing.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.NotificationActorFollow do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"follower", :struct, PeerTube.Model.ActorInfo, options)
    |> deserialize(:"following", :struct, PeerTube.Model.NotificationActorFollowFollowing, options)
  end
end

