# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.NotificationVideoImport do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"video",
    :"torrentName",
    :"magnetUri",
    :"targetUri"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"video" => PeerTube.Model.VideoInfo.t | nil,
    :"torrentName" => String.t | nil,
    :"magnetUri" => String.t | nil,
    :"targetUri" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.NotificationVideoImport do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"video", :struct, PeerTube.Model.VideoInfo, options)
  end
end

