# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.NotificationSettingValue do
  @moduledoc """
  Notification type - `0` NONE - `1` WEB - `2` EMAIL 
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.NotificationSettingValue do
  def decode(value, _options) do
    value
  end
end

