# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.Plugin do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"type",
    :"latestVersion",
    :"version",
    :"enabled",
    :"uninstalled",
    :"peertubeEngine",
    :"description",
    :"homepage",
    :"settings",
    :"createdAt",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"type" => integer() | nil,
    :"latestVersion" => String.t | nil,
    :"version" => String.t | nil,
    :"enabled" => boolean() | nil,
    :"uninstalled" => boolean() | nil,
    :"peertubeEngine" => String.t | nil,
    :"description" => String.t | nil,
    :"homepage" => String.t | nil,
    :"settings" => %{optional(String.t) => map()} | nil,
    :"createdAt" => DateTime.t | nil,
    :"updatedAt" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.Plugin do
  def decode(value, _options) do
    value
  end
end

