# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.RegisterUser do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"username",
    :"password",
    :"email",
    :"displayName",
    :"channel"
  ]

  @type t :: %__MODULE__{
    :"username" => String.t,
    :"password" => String.t,
    :"email" => String.t,
    :"displayName" => String.t | nil,
    :"channel" => PeerTube.Model.RegisterUserChannel.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.RegisterUser do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"channel", :struct, PeerTube.Model.RegisterUserChannel, options)
  end
end

