# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigAboutInstance do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"shortDescription",
    :"description",
    :"terms"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"shortDescription" => String.t | nil,
    :"description" => String.t | nil,
    :"terms" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigAboutInstance do
  def decode(value, _options) do
    value
  end
end

