# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigTranscoding do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"hls",
    :"webtorrent",
    :"enabledResolutions"
  ]

  @type t :: %__MODULE__{
    :"hls" => PeerTube.Model.ServerConfigEmail.t | nil,
    :"webtorrent" => PeerTube.Model.ServerConfigEmail.t | nil,
    :"enabledResolutions" => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigTranscoding do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"hls", :struct, PeerTube.Model.ServerConfigEmail, options)
    |> deserialize(:"webtorrent", :struct, PeerTube.Model.ServerConfigEmail, options)
  end
end

