# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigTrending do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"videos"
  ]

  @type t :: %__MODULE__{
    :"videos" => PeerTube.Model.ServerConfigTrendingVideos.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigTrending do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"videos", :struct, PeerTube.Model.ServerConfigTrendingVideos, options)
  end
end

