# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigSearch do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"remoteUri"
  ]

  @type t :: %__MODULE__{
    :"remoteUri" => PeerTube.Model.ServerConfigSearchRemoteUri.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigSearch do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"remoteUri", :struct, PeerTube.Model.ServerConfigSearchRemoteUri, options)
  end
end

