# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigFollowingsInstance do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"autoFollowIndex"
  ]

  @type t :: %__MODULE__{
    :"autoFollowIndex" => PeerTube.Model.ServerConfigFollowingsInstanceAutoFollowIndex.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigFollowingsInstance do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"autoFollowIndex", :struct, PeerTube.Model.ServerConfigFollowingsInstanceAutoFollowIndex, options)
  end
end

