# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigVideoImage do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"extensions",
    :"size"
  ]

  @type t :: %__MODULE__{
    :"extensions" => [String.t] | nil,
    :"size" => PeerTube.Model.ServerConfigAvatarFileSize.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigVideoImage do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"size", :struct, PeerTube.Model.ServerConfigAvatarFileSize, options)
  end
end

