# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigCustomTranscoding do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"enabled",
    :"allowAdditionalExtensions",
    :"allowAudioFiles",
    :"threads",
    :"resolutions",
    :"hls"
  ]

  @type t :: %__MODULE__{
    :"enabled" => boolean() | nil,
    :"allowAdditionalExtensions" => boolean() | nil,
    :"allowAudioFiles" => boolean() | nil,
    :"threads" => integer() | nil,
    :"resolutions" => PeerTube.Model.ServerConfigCustomTranscodingResolutions.t | nil,
    :"hls" => PeerTube.Model.ServerConfigEmail.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigCustomTranscoding do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"resolutions", :struct, PeerTube.Model.ServerConfigCustomTranscodingResolutions, options)
    |> deserialize(:"hls", :struct, PeerTube.Model.ServerConfigEmail, options)
  end
end

