# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"instance",
    :"search",
    :"plugin",
    :"theme",
    :"email",
    :"contactForm",
    :"serverVersion",
    :"serverCommit",
    :"signup",
    :"transcoding",
    :"import",
    :"autoBlacklist",
    :"avatar",
    :"video",
    :"videoCaption",
    :"user",
    :"trending",
    :"tracker",
    :"followings"
  ]

  @type t :: %__MODULE__{
    :"instance" => PeerTube.Model.ServerConfigInstance.t | nil,
    :"search" => PeerTube.Model.ServerConfigSearch.t | nil,
    :"plugin" => PeerTube.Model.ServerConfigPlugin.t | nil,
    :"theme" => PeerTube.Model.ServerConfigPlugin.t | nil,
    :"email" => PeerTube.Model.ServerConfigEmail.t | nil,
    :"contactForm" => PeerTube.Model.ServerConfigEmail.t | nil,
    :"serverVersion" => String.t | nil,
    :"serverCommit" => String.t | nil,
    :"signup" => PeerTube.Model.ServerConfigSignup.t | nil,
    :"transcoding" => PeerTube.Model.ServerConfigTranscoding.t | nil,
    :"import" => PeerTube.Model.ServerConfigImport.t | nil,
    :"autoBlacklist" => PeerTube.Model.ServerConfigAutoBlacklist.t | nil,
    :"avatar" => PeerTube.Model.ServerConfigAvatar.t | nil,
    :"video" => PeerTube.Model.ServerConfigVideo.t | nil,
    :"videoCaption" => PeerTube.Model.ServerConfigVideoCaption.t | nil,
    :"user" => PeerTube.Model.ServerConfigUser.t | nil,
    :"trending" => PeerTube.Model.ServerConfigTrending.t | nil,
    :"tracker" => PeerTube.Model.ServerConfigEmail.t | nil,
    :"followings" => PeerTube.Model.ServerConfigFollowings.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfig do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"instance", :struct, PeerTube.Model.ServerConfigInstance, options)
    |> deserialize(:"search", :struct, PeerTube.Model.ServerConfigSearch, options)
    |> deserialize(:"plugin", :struct, PeerTube.Model.ServerConfigPlugin, options)
    |> deserialize(:"theme", :struct, PeerTube.Model.ServerConfigPlugin, options)
    |> deserialize(:"email", :struct, PeerTube.Model.ServerConfigEmail, options)
    |> deserialize(:"contactForm", :struct, PeerTube.Model.ServerConfigEmail, options)
    |> deserialize(:"signup", :struct, PeerTube.Model.ServerConfigSignup, options)
    |> deserialize(:"transcoding", :struct, PeerTube.Model.ServerConfigTranscoding, options)
    |> deserialize(:"import", :struct, PeerTube.Model.ServerConfigImport, options)
    |> deserialize(:"autoBlacklist", :struct, PeerTube.Model.ServerConfigAutoBlacklist, options)
    |> deserialize(:"avatar", :struct, PeerTube.Model.ServerConfigAvatar, options)
    |> deserialize(:"video", :struct, PeerTube.Model.ServerConfigVideo, options)
    |> deserialize(:"videoCaption", :struct, PeerTube.Model.ServerConfigVideoCaption, options)
    |> deserialize(:"user", :struct, PeerTube.Model.ServerConfigUser, options)
    |> deserialize(:"trending", :struct, PeerTube.Model.ServerConfigTrending, options)
    |> deserialize(:"tracker", :struct, PeerTube.Model.ServerConfigEmail, options)
    |> deserialize(:"followings", :struct, PeerTube.Model.ServerConfigFollowings, options)
  end
end

