# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigVideoCaption do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"file"
  ]

  @type t :: %__MODULE__{
    :"file" => PeerTube.Model.ServerConfigVideoCaptionFile.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigVideoCaption do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"file", :struct, PeerTube.Model.ServerConfigVideoCaptionFile, options)
  end
end

