# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigCustomServicesTwitter do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"username",
    :"whitelisted"
  ]

  @type t :: %__MODULE__{
    :"username" => String.t | nil,
    :"whitelisted" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigCustomServicesTwitter do
  def decode(value, _options) do
    value
  end
end

