# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigCustomTranscodingResolutions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"240p",
    :"360p",
    :"480p",
    :"720p",
    :"1080p",
    :"1440p",
    :"2160p"
  ]

  @type t :: %__MODULE__{
    :"240p" => boolean() | nil,
    :"360p" => boolean() | nil,
    :"480p" => boolean() | nil,
    :"720p" => boolean() | nil,
    :"1080p" => boolean() | nil,
    :"1440p" => boolean() | nil,
    :"2160p" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigCustomTranscodingResolutions do
  def decode(value, _options) do
    value
  end
end

