# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigSearchRemoteUri do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"users",
    :"anonymous"
  ]

  @type t :: %__MODULE__{
    :"users" => boolean() | nil,
    :"anonymous" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigSearchRemoteUri do
  def decode(value, _options) do
    value
  end
end

