# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigInstanceCustomizations do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"javascript",
    :"css"
  ]

  @type t :: %__MODULE__{
    :"javascript" => String.t | nil,
    :"css" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigInstanceCustomizations do
  def decode(value, _options) do
    value
  end
end

