# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigAvatar do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"file",
    :"extensions"
  ]

  @type t :: %__MODULE__{
    :"file" => PeerTube.Model.ServerConfigAvatarFile.t | nil,
    :"extensions" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigAvatar do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"file", :struct, PeerTube.Model.ServerConfigAvatarFile, options)
  end
end

