# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigAutoBlacklistVideos do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ofUsers"
  ]

  @type t :: %__MODULE__{
    :"ofUsers" => PeerTube.Model.ServerConfigEmail.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigAutoBlacklistVideos do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ofUsers", :struct, PeerTube.Model.ServerConfigEmail, options)
  end
end

