# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigImportVideos do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"http",
    :"torrent"
  ]

  @type t :: %__MODULE__{
    :"http" => PeerTube.Model.ServerConfigEmail.t | nil,
    :"torrent" => PeerTube.Model.ServerConfigEmail.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigImportVideos do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"http", :struct, PeerTube.Model.ServerConfigEmail, options)
    |> deserialize(:"torrent", :struct, PeerTube.Model.ServerConfigEmail, options)
  end
end

