# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.ServerConfigUser do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"videoQuota",
    :"videoQuotaDaily"
  ]

  @type t :: %__MODULE__{
    :"videoQuota" => integer() | nil,
    :"videoQuotaDaily" => integer() | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.ServerConfigUser do
  def decode(value, _options) do
    value
  end
end

