# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.UpdateMe do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"password",
    :"email",
    :"displayNSFW",
    :"autoPlayVideo"
  ]

  @type t :: %__MODULE__{
    :"password" => String.t,
    :"email" => String.t,
    :"displayNSFW" => String.t,
    :"autoPlayVideo" => boolean()
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.UpdateMe do
  def decode(value, _options) do
    value
  end
end

