# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.User do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"username",
    :"email",
    :"pluginAuth",
    :"theme",
    :"emailVerified",
    :"nsfwPolicy",
    :"webtorrentEnabled",
    :"autoPlayVideo",
    :"role",
    :"roleLabel",
    :"videoQuota",
    :"videoQuotaDaily",
    :"videosCount",
    :"abusesCount",
    :"abusesAcceptedCount",
    :"abusesCreatedCount",
    :"videoCommentsCount",
    :"noInstanceConfigWarningModal",
    :"noWelcomeModal",
    :"blocked",
    :"blockedReason",
    :"createdAt",
    :"account",
    :"videoChannels"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"username" => String.t | nil,
    :"email" => String.t | nil,
    :"pluginAuth" => String.t | nil,
    :"theme" => String.t | nil,
    :"emailVerified" => boolean() | nil,
    :"nsfwPolicy" => PeerTube.Model.NsfwPolicy.t | nil,
    :"webtorrentEnabled" => boolean() | nil,
    :"autoPlayVideo" => boolean() | nil,
    :"role" => PeerTube.Model.UserRole.t | nil,
    :"roleLabel" => String.t | nil,
    :"videoQuota" => integer() | nil,
    :"videoQuotaDaily" => integer() | nil,
    :"videosCount" => integer() | nil,
    :"abusesCount" => integer() | nil,
    :"abusesAcceptedCount" => integer() | nil,
    :"abusesCreatedCount" => integer() | nil,
    :"videoCommentsCount" => integer() | nil,
    :"noInstanceConfigWarningModal" => boolean() | nil,
    :"noWelcomeModal" => boolean() | nil,
    :"blocked" => boolean() | nil,
    :"blockedReason" => String.t | nil,
    :"createdAt" => String.t | nil,
    :"account" => PeerTube.Model.Account.t | nil,
    :"videoChannels" => [PeerTube.Model.VideoChannel.t] | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.User do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"nsfwPolicy", :struct, PeerTube.Model.NsfwPolicy, options)
    |> deserialize(:"role", :struct, PeerTube.Model.UserRole, options)
    |> deserialize(:"account", :struct, PeerTube.Model.Account, options)
    |> deserialize(:"videoChannels", :list, PeerTube.Model.VideoChannel, options)
  end
end

