# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoCommentThreadTree do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"comment",
    :"children"
  ]

  @type t :: %__MODULE__{
    :"comment" => PeerTube.Model.VideoComment.t | nil,
    :"children" => [PeerTube.Model.VideoCommentThreadTree.t] | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoCommentThreadTree do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"comment", :struct, PeerTube.Model.VideoComment, options)
    |> deserialize(:"children", :list, PeerTube.Model.VideoCommentThreadTree, options)
  end
end

