# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoRedundancy do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"url",
    :"uuid",
    :"redundancies"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"name" => String.t | nil,
    :"url" => String.t | nil,
    :"uuid" => String.t | nil,
    :"redundancies" => PeerTube.Model.VideoRedundancyRedundancies.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoRedundancy do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"redundancies", :struct, PeerTube.Model.VideoRedundancyRedundancies, options)
  end
end

