# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoRating do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"video",
    :"rating"
  ]

  @type t :: %__MODULE__{
    :"video" => PeerTube.Model.Video.t,
    :"rating" => float()
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoRating do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"video", :struct, PeerTube.Model.Video, options)
  end
end

