# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoScheduledUpdate do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"privacy",
    :"updateAt"
  ]

  @type t :: %__MODULE__{
    :"privacy" => PeerTube.Model.VideoPrivacySet.t | nil,
    :"updateAt" => Date.t
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoScheduledUpdate do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"privacy", :struct, PeerTube.Model.VideoPrivacySet, options)
    |> deserialize(:"updateAt", :date, nil, options)
  end
end

