# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoImport do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"targetUrl",
    :"magnetUri",
    :"torrentName",
    :"state",
    :"error",
    :"createdAt",
    :"updatedAt",
    :"video"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"targetUrl" => String.t | nil,
    :"magnetUri" => String.t | nil,
    :"torrentName" => String.t | nil,
    :"state" => PeerTube.Model.VideoImportStateConstant.t | nil,
    :"error" => String.t | nil,
    :"createdAt" => DateTime.t | nil,
    :"updatedAt" => DateTime.t | nil,
    :"video" => PeerTube.Model.Video.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoImport do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"state", :struct, PeerTube.Model.VideoImportStateConstant, options)
    |> deserialize(:"video", :struct, PeerTube.Model.Video, options)
  end
end

