# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoFile do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"magnetUri",
    :"resolution",
    :"size",
    :"torrentUrl",
    :"torrentDownloadUrl",
    :"fileUrl",
    :"fileDownloadUrl",
    :"fps",
    :"metadataUrl"
  ]

  @type t :: %__MODULE__{
    :"magnetUri" => String.t | nil,
    :"resolution" => PeerTube.Model.VideoResolutionConstant.t | nil,
    :"size" => integer() | nil,
    :"torrentUrl" => String.t | nil,
    :"torrentDownloadUrl" => String.t | nil,
    :"fileUrl" => String.t | nil,
    :"fileDownloadUrl" => String.t | nil,
    :"fps" => float() | nil,
    :"metadataUrl" => String.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoFile do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"resolution", :struct, PeerTube.Model.VideoResolutionConstant, options)
  end
end

