# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoComment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"url",
    :"text",
    :"threadId",
    :"inReplyToCommentId",
    :"videoId",
    :"createdAt",
    :"updatedAt",
    :"totalRepliesFromVideoAuthor",
    :"totalReplies",
    :"account"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"url" => String.t | nil,
    :"text" => String.t | nil,
    :"threadId" => integer() | nil,
    :"inReplyToCommentId" => integer() | nil,
    :"videoId" => integer() | nil,
    :"createdAt" => DateTime.t | nil,
    :"updatedAt" => DateTime.t | nil,
    :"totalRepliesFromVideoAuthor" => integer() | nil,
    :"totalReplies" => integer() | nil,
    :"account" => PeerTube.Model.Account.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoComment do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"account", :struct, PeerTube.Model.Account, options)
  end
end

