# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoChannel do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"displayName",
    :"description",
    :"isLocal",
    :"ownerAccount"
  ]

  @type t :: %__MODULE__{
    :"displayName" => String.t | nil,
    :"description" => String.t | nil,
    :"isLocal" => boolean() | nil,
    :"ownerAccount" => PeerTube.Model.VideoChannelOwnerAccount.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoChannel do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ownerAccount", :struct, PeerTube.Model.VideoChannelOwnerAccount, options)
  end
end

