# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoUploadResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"video"
  ]

  @type t :: %__MODULE__{
    :"video" => PeerTube.Model.VideoUploadResponseVideo.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoUploadResponse do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"video", :struct, PeerTube.Model.VideoUploadResponseVideo, options)
  end
end

