# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoPlaylistTypeSet do
  @moduledoc """
  The video playlist type (Regular = `1`, Watch Later = `2`)
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoPlaylistTypeSet do
  def decode(value, _options) do
    value
  end
end

