# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoPlaylist do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"createdAt",
    :"updatedAt",
    :"description",
    :"uuid",
    :"displayName",
    :"isLocal",
    :"videoLength",
    :"thumbnailPath",
    :"privacy",
    :"type",
    :"ownerAccount",
    :"videoChannel"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"createdAt" => DateTime.t | nil,
    :"updatedAt" => DateTime.t | nil,
    :"description" => String.t | nil,
    :"uuid" => String.t | nil,
    :"displayName" => String.t | nil,
    :"isLocal" => boolean() | nil,
    :"videoLength" => integer() | nil,
    :"thumbnailPath" => String.t | nil,
    :"privacy" => PeerTube.Model.VideoPlaylistPrivacyConstant.t | nil,
    :"type" => PeerTube.Model.VideoPlaylistTypeConstant.t | nil,
    :"ownerAccount" => PeerTube.Model.AccountSummary.t | nil,
    :"videoChannel" => PeerTube.Model.VideoChannelSummary.t | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoPlaylist do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"privacy", :struct, PeerTube.Model.VideoPlaylistPrivacyConstant, options)
    |> deserialize(:"type", :struct, PeerTube.Model.VideoPlaylistTypeConstant, options)
    |> deserialize(:"ownerAccount", :struct, PeerTube.Model.AccountSummary, options)
    |> deserialize(:"videoChannel", :struct, PeerTube.Model.VideoChannelSummary, options)
  end
end

