# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule PeerTube.Model.VideoRedundancyRedundancies do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"files",
    :"streamingPlaylists"
  ]

  @type t :: %__MODULE__{
    :"files" => [PeerTube.Model.FileRedundancyInformation.t] | nil,
    :"streamingPlaylists" => [PeerTube.Model.FileRedundancyInformation.t] | nil
  }
end

defimpl Poison.Decoder, for: PeerTube.Model.VideoRedundancyRedundancies do
  import PeerTube.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"files", :list, PeerTube.Model.FileRedundancyInformation, options)
    |> deserialize(:"streamingPlaylists", :list, PeerTube.Model.FileRedundancyInformation, options)
  end
end

